services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces

    command: sleep infinity

  valkey:
    image: valkey/valkey:latest

  vector-db:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data: