services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces

    command: sleep infinity

  valkey:
    image: valkey/valkey:latest

  vector-db:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
    volumes:
      - qdrant_data:/qdrant/storage

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/mongo/storage
  
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin #mongodb uname
      ME_CONFIG_MONGODB_AUTH_PASSWORD: admin #mongodb pass
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin #For browser
      ME_CONFIG_BASICAUTH_PASSWORD: admin #For browser
    depends_on:
      - mongodb

volumes:
  qdrant_data:
  mongo_data:
